### ISSUE TITLE
Dataset, Checkpoint and Adaptation Code is Available

### ISSUE THREAD

**Issue by WenWeiTHU** [thuml/Large-Time-Series-Model#2]
See eed7df5fce425b1962c4441cf890f1da235114fe, including:
* Up to date with [the camera-ready version](https://arxiv.org/abs/2402.02368).
* UTSD-12G is released in the [HuggingFace](https://huggingface.co/datasets/thuml/UTSD).
* Support multiple tasks: IMS/DMS [forecasting](https://github.com/thuml/Large-Time-Series-Model/tree/main/scripts/forecast), segment-level [imputation](https://github.com/thuml/Large-Time-Series-Model/tree/main/scripts/imputation), and [anomaly detection](https://github.com/thuml/Large-Time-Series-Model/tree/main/scripts/anomaly_detection) on UCR.

**Comment by manmanjun** [comment]
Hi, would you release the pretraining code?

**Comment by WHU-HZY** [comment]
Why Timer_forecast_1.0.ckpt is much larger than others? I mean, the paper said the single foundation model can adapt on multiple downsteam tasks rather than the different model to different tasks, maybe it's a problem with my understanding, Could you please tell the difference between several checkpoints? Thanks.
